namespace ContAlumnos
{
    partial class Menu
    {
        /// <summary>
        /// Variable del diseñador necesaria.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Limpiar los recursos que se estén usando.
        /// </summary>
        /// <param name="disposing">true si los recursos administrados se deben desechar; false en caso contrario.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Código generado por el Diseñador de Windows Forms

        /// <summary>
        /// Método necesario para admitir el Diseñador. No se puede modificar
        /// el contenido de este método con el editor de código.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Menu));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.label2 = new System.Windows.Forms.Label();
            this.bunifuFormControlBox1 = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.panel2 = new System.Windows.Forms.Panel();
            this.btnocultar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnSalir = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnconfiguracion = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnmaestros = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnestudiantes = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnInicio = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.panel3 = new System.Windows.Forms.Panel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btnuser = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.titulo = new System.Windows.Forms.Label();
            this.panelDesktop = new System.Windows.Forms.Panel();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.panel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.Transparent;
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.bunifuFormControlBox1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1200, 44);
            this.panel1.TabIndex = 0;
            this.panel1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.panel1_MouseDown);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Century Gothic", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.SystemColors.AppWorkspace;
            this.label2.Location = new System.Drawing.Point(41, 14);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(78, 16);
            this.label2.TabIndex = 4;
            this.label2.Text = "ContAlumnos";
            this.label2.MouseDown += new System.Windows.Forms.MouseEventHandler(this.label1_MouseDown);
            // 
            // bunifuFormControlBox1
            // 
            this.bunifuFormControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuFormControlBox1.BunifuFormDrag = null;
            this.bunifuFormControlBox1.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.BorderRadius = 35;
            this.bunifuFormControlBox1.CloseBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.CloseBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.CloseBoxOptions.Icon")));
            this.bunifuFormControlBox1.CloseBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.CloseBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.CloseBoxOptions.IconHoverColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconPressedColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.bunifuFormControlBox1.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.HelpBox = false;
            this.bunifuFormControlBox1.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.HelpBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.HelpBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.HelpBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.HelpBoxOptions.Icon")));
            this.bunifuFormControlBox1.HelpBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.bunifuFormControlBox1.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Location = new System.Drawing.Point(1094, 3);
            this.bunifuFormControlBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuFormControlBox1.MaximizeBox = false;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Enabled = false;
            this.bunifuFormControlBox1.MaximizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.IconAlt")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.bunifuFormControlBox1.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.MinimizeBox = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BorderRadius = 35;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MinimizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.bunifuFormControlBox1.MinimizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Name = "bunifuFormControlBox1";
            this.bunifuFormControlBox1.ShowDesignBorders = false;
            this.bunifuFormControlBox1.Size = new System.Drawing.Size(95, 41);
            this.bunifuFormControlBox1.TabIndex = 5;
            this.bunifuFormControlBox1.CloseClicked += new System.EventHandler(this.bunifuFormControlBox1_CloseClicked);
            this.bunifuFormControlBox1.HelpClicked += new System.EventHandler(this.bunifuFormControlBox1_HelpClicked);
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.White;
            this.panel2.Controls.Add(this.btnocultar);
            this.panel2.Controls.Add(this.btnSalir);
            this.panel2.Controls.Add(this.btnconfiguracion);
            this.panel2.Controls.Add(this.btnmaestros);
            this.panel2.Controls.Add(this.btnestudiantes);
            this.panel2.Controls.Add(this.btnInicio);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel2.Location = new System.Drawing.Point(0, 44);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(262, 556);
            this.panel2.TabIndex = 1;
            // 
            // btnocultar
            // 
            this.btnocultar.AllowAnimations = true;
            this.btnocultar.AllowMouseEffects = true;
            this.btnocultar.AllowToggling = false;
            this.btnocultar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnocultar.AnimationSpeed = 200;
            this.btnocultar.AutoGenerateColors = false;
            this.btnocultar.AutoRoundBorders = false;
            this.btnocultar.AutoSizeLeftIcon = false;
            this.btnocultar.AutoSizeRightIcon = true;
            this.btnocultar.BackColor = System.Drawing.Color.Transparent;
            this.btnocultar.BackColor1 = System.Drawing.Color.Transparent;
            this.btnocultar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnocultar.BackgroundImage")));
            this.btnocultar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnocultar.ButtonText = "";
            this.btnocultar.ButtonTextMarginLeft = 0;
            this.btnocultar.ColorContrastOnClick = 45;
            this.btnocultar.ColorContrastOnHover = 45;
            this.btnocultar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnocultar.CustomizableEdges = borderEdges1;
            this.btnocultar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnocultar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnocultar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnocultar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnocultar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnocultar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnocultar.ForeColor = System.Drawing.Color.White;
            this.btnocultar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnocultar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnocultar.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.btnocultar.IconMarginLeft = 11;
            this.btnocultar.IconPadding = 10;
            this.btnocultar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnocultar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnocultar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnocultar.IconSize = 30;
            this.btnocultar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnocultar.IdleBorderRadius = 35;
            this.btnocultar.IdleBorderThickness = 1;
            this.btnocultar.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnocultar.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnocultar.IdleIconLeftImage")));
            this.btnocultar.IdleIconRightImage = null;
            this.btnocultar.IndicateFocus = false;
            this.btnocultar.Location = new System.Drawing.Point(210, 35);
            this.btnocultar.Name = "btnocultar";
            this.btnocultar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnocultar.OnDisabledState.BorderRadius = 35;
            this.btnocultar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnocultar.OnDisabledState.BorderThickness = 1;
            this.btnocultar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnocultar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnocultar.OnDisabledState.IconLeftImage = null;
            this.btnocultar.OnDisabledState.IconRightImage = null;
            this.btnocultar.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.btnocultar.onHoverState.BorderRadius = 35;
            this.btnocultar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnocultar.onHoverState.BorderThickness = 1;
            this.btnocultar.onHoverState.FillColor = System.Drawing.Color.Empty;
            this.btnocultar.onHoverState.ForeColor = System.Drawing.Color.Transparent;
            this.btnocultar.onHoverState.IconLeftImage = null;
            this.btnocultar.onHoverState.IconRightImage = null;
            this.btnocultar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnocultar.OnIdleState.BorderRadius = 35;
            this.btnocultar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnocultar.OnIdleState.BorderThickness = 1;
            this.btnocultar.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnocultar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnocultar.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnocultar.OnIdleState.IconLeftImage")));
            this.btnocultar.OnIdleState.IconRightImage = null;
            this.btnocultar.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.btnocultar.OnPressedState.BorderRadius = 35;
            this.btnocultar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnocultar.OnPressedState.BorderThickness = 1;
            this.btnocultar.OnPressedState.FillColor = System.Drawing.Color.Empty;
            this.btnocultar.OnPressedState.ForeColor = System.Drawing.Color.Transparent;
            this.btnocultar.OnPressedState.IconLeftImage = null;
            this.btnocultar.OnPressedState.IconRightImage = null;
            this.btnocultar.Size = new System.Drawing.Size(44, 39);
            this.btnocultar.TabIndex = 5;
            this.btnocultar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnocultar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnocultar.TextMarginLeft = 0;
            this.btnocultar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnocultar.UseDefaultRadiusAndThickness = true;
            this.btnocultar.Click += new System.EventHandler(this.bunifuButton25_Click);
            // 
            // btnSalir
            // 
            this.btnSalir.AllowAnimations = true;
            this.btnSalir.AllowMouseEffects = true;
            this.btnSalir.AllowToggling = false;
            this.btnSalir.AnimationSpeed = 200;
            this.btnSalir.AutoGenerateColors = false;
            this.btnSalir.AutoRoundBorders = false;
            this.btnSalir.AutoSizeLeftIcon = false;
            this.btnSalir.AutoSizeRightIcon = true;
            this.btnSalir.BackColor = System.Drawing.Color.Transparent;
            this.btnSalir.BackColor1 = System.Drawing.Color.Transparent;
            this.btnSalir.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSalir.BackgroundImage")));
            this.btnSalir.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSalir.ButtonText = "Salir";
            this.btnSalir.ButtonTextMarginLeft = 0;
            this.btnSalir.ColorContrastOnClick = 45;
            this.btnSalir.ColorContrastOnHover = 45;
            this.btnSalir.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnSalir.CustomizableEdges = borderEdges2;
            this.btnSalir.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSalir.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSalir.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSalir.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSalir.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnSalir.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSalir.ForeColor = System.Drawing.SystemColors.WindowText;
            this.btnSalir.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSalir.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSalir.IconLeftPadding = new System.Windows.Forms.Padding(25, 3, 3, 3);
            this.btnSalir.IconMarginLeft = 11;
            this.btnSalir.IconPadding = 10;
            this.btnSalir.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSalir.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSalir.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSalir.IconSize = 25;
            this.btnSalir.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnSalir.IdleBorderRadius = 35;
            this.btnSalir.IdleBorderThickness = 1;
            this.btnSalir.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnSalir.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnSalir.IdleIconLeftImage")));
            this.btnSalir.IdleIconRightImage = null;
            this.btnSalir.IndicateFocus = false;
            this.btnSalir.Location = new System.Drawing.Point(13, 484);
            this.btnSalir.Name = "btnSalir";
            this.btnSalir.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSalir.OnDisabledState.BorderRadius = 35;
            this.btnSalir.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSalir.OnDisabledState.BorderThickness = 1;
            this.btnSalir.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSalir.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSalir.OnDisabledState.IconLeftImage = null;
            this.btnSalir.OnDisabledState.IconRightImage = null;
            this.btnSalir.onHoverState.BorderColor = System.Drawing.Color.LightSkyBlue;
            this.btnSalir.onHoverState.BorderRadius = 35;
            this.btnSalir.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSalir.onHoverState.BorderThickness = 1;
            this.btnSalir.onHoverState.FillColor = System.Drawing.Color.LightSkyBlue;
            this.btnSalir.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSalir.onHoverState.IconLeftImage = null;
            this.btnSalir.onHoverState.IconRightImage = null;
            this.btnSalir.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSalir.OnIdleState.BorderRadius = 35;
            this.btnSalir.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSalir.OnIdleState.BorderThickness = 1;
            this.btnSalir.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnSalir.OnIdleState.ForeColor = System.Drawing.SystemColors.WindowText;
            this.btnSalir.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnSalir.OnIdleState.IconLeftImage")));
            this.btnSalir.OnIdleState.IconRightImage = null;
            this.btnSalir.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSalir.OnPressedState.BorderRadius = 35;
            this.btnSalir.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSalir.OnPressedState.BorderThickness = 1;
            this.btnSalir.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSalir.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSalir.OnPressedState.IconLeftImage = null;
            this.btnSalir.OnPressedState.IconRightImage = null;
            this.btnSalir.Size = new System.Drawing.Size(241, 61);
            this.btnSalir.TabIndex = 4;
            this.btnSalir.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSalir.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSalir.TextMarginLeft = 0;
            this.btnSalir.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSalir.UseDefaultRadiusAndThickness = true;
            this.btnSalir.Click += new System.EventHandler(this.btnSalir_Click);
            // 
            // btnconfiguracion
            // 
            this.btnconfiguracion.AllowAnimations = true;
            this.btnconfiguracion.AllowMouseEffects = true;
            this.btnconfiguracion.AllowToggling = false;
            this.btnconfiguracion.AnimationSpeed = 200;
            this.btnconfiguracion.AutoGenerateColors = false;
            this.btnconfiguracion.AutoRoundBorders = false;
            this.btnconfiguracion.AutoSizeLeftIcon = false;
            this.btnconfiguracion.AutoSizeRightIcon = true;
            this.btnconfiguracion.BackColor = System.Drawing.Color.Transparent;
            this.btnconfiguracion.BackColor1 = System.Drawing.Color.Transparent;
            this.btnconfiguracion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnconfiguracion.BackgroundImage")));
            this.btnconfiguracion.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnconfiguracion.ButtonText = "Configuracion";
            this.btnconfiguracion.ButtonTextMarginLeft = 0;
            this.btnconfiguracion.ColorContrastOnClick = 45;
            this.btnconfiguracion.ColorContrastOnHover = 45;
            this.btnconfiguracion.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnconfiguracion.CustomizableEdges = borderEdges3;
            this.btnconfiguracion.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnconfiguracion.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnconfiguracion.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnconfiguracion.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnconfiguracion.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnconfiguracion.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnconfiguracion.ForeColor = System.Drawing.SystemColors.WindowText;
            this.btnconfiguracion.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnconfiguracion.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnconfiguracion.IconLeftPadding = new System.Windows.Forms.Padding(25, 3, 3, 3);
            this.btnconfiguracion.IconMarginLeft = 11;
            this.btnconfiguracion.IconPadding = 10;
            this.btnconfiguracion.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnconfiguracion.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnconfiguracion.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnconfiguracion.IconSize = 25;
            this.btnconfiguracion.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnconfiguracion.IdleBorderRadius = 35;
            this.btnconfiguracion.IdleBorderThickness = 1;
            this.btnconfiguracion.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnconfiguracion.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnconfiguracion.IdleIconLeftImage")));
            this.btnconfiguracion.IdleIconRightImage = null;
            this.btnconfiguracion.IndicateFocus = false;
            this.btnconfiguracion.Location = new System.Drawing.Point(13, 335);
            this.btnconfiguracion.Name = "btnconfiguracion";
            this.btnconfiguracion.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnconfiguracion.OnDisabledState.BorderRadius = 35;
            this.btnconfiguracion.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnconfiguracion.OnDisabledState.BorderThickness = 1;
            this.btnconfiguracion.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnconfiguracion.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnconfiguracion.OnDisabledState.IconLeftImage = null;
            this.btnconfiguracion.OnDisabledState.IconRightImage = null;
            this.btnconfiguracion.onHoverState.BorderColor = System.Drawing.Color.LightSkyBlue;
            this.btnconfiguracion.onHoverState.BorderRadius = 35;
            this.btnconfiguracion.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnconfiguracion.onHoverState.BorderThickness = 1;
            this.btnconfiguracion.onHoverState.FillColor = System.Drawing.Color.LightSkyBlue;
            this.btnconfiguracion.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnconfiguracion.onHoverState.IconLeftImage = null;
            this.btnconfiguracion.onHoverState.IconRightImage = null;
            this.btnconfiguracion.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnconfiguracion.OnIdleState.BorderRadius = 35;
            this.btnconfiguracion.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnconfiguracion.OnIdleState.BorderThickness = 1;
            this.btnconfiguracion.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnconfiguracion.OnIdleState.ForeColor = System.Drawing.SystemColors.WindowText;
            this.btnconfiguracion.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnconfiguracion.OnIdleState.IconLeftImage")));
            this.btnconfiguracion.OnIdleState.IconRightImage = null;
            this.btnconfiguracion.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnconfiguracion.OnPressedState.BorderRadius = 35;
            this.btnconfiguracion.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnconfiguracion.OnPressedState.BorderThickness = 1;
            this.btnconfiguracion.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnconfiguracion.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnconfiguracion.OnPressedState.IconLeftImage = null;
            this.btnconfiguracion.OnPressedState.IconRightImage = null;
            this.btnconfiguracion.Size = new System.Drawing.Size(241, 60);
            this.btnconfiguracion.TabIndex = 3;
            this.btnconfiguracion.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnconfiguracion.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnconfiguracion.TextMarginLeft = 0;
            this.btnconfiguracion.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnconfiguracion.UseDefaultRadiusAndThickness = true;
            this.btnconfiguracion.Click += new System.EventHandler(this.btnconfiguracion_Click);
            // 
            // btnmaestros
            // 
            this.btnmaestros.AllowAnimations = true;
            this.btnmaestros.AllowMouseEffects = true;
            this.btnmaestros.AllowToggling = false;
            this.btnmaestros.AnimationSpeed = 200;
            this.btnmaestros.AutoGenerateColors = false;
            this.btnmaestros.AutoRoundBorders = false;
            this.btnmaestros.AutoSizeLeftIcon = false;
            this.btnmaestros.AutoSizeRightIcon = true;
            this.btnmaestros.BackColor = System.Drawing.Color.Transparent;
            this.btnmaestros.BackColor1 = System.Drawing.Color.Transparent;
            this.btnmaestros.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnmaestros.BackgroundImage")));
            this.btnmaestros.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnmaestros.ButtonText = "Manejo Maestro";
            this.btnmaestros.ButtonTextMarginLeft = 0;
            this.btnmaestros.ColorContrastOnClick = 45;
            this.btnmaestros.ColorContrastOnHover = 45;
            this.btnmaestros.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnmaestros.CustomizableEdges = borderEdges4;
            this.btnmaestros.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnmaestros.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnmaestros.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnmaestros.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnmaestros.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnmaestros.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnmaestros.ForeColor = System.Drawing.SystemColors.WindowText;
            this.btnmaestros.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnmaestros.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnmaestros.IconLeftPadding = new System.Windows.Forms.Padding(25, 3, 3, 3);
            this.btnmaestros.IconMarginLeft = 11;
            this.btnmaestros.IconPadding = 10;
            this.btnmaestros.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnmaestros.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnmaestros.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnmaestros.IconSize = 25;
            this.btnmaestros.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnmaestros.IdleBorderRadius = 35;
            this.btnmaestros.IdleBorderThickness = 1;
            this.btnmaestros.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnmaestros.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnmaestros.IdleIconLeftImage")));
            this.btnmaestros.IdleIconRightImage = null;
            this.btnmaestros.IndicateFocus = false;
            this.btnmaestros.Location = new System.Drawing.Point(13, 267);
            this.btnmaestros.Name = "btnmaestros";
            this.btnmaestros.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnmaestros.OnDisabledState.BorderRadius = 35;
            this.btnmaestros.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnmaestros.OnDisabledState.BorderThickness = 1;
            this.btnmaestros.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnmaestros.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnmaestros.OnDisabledState.IconLeftImage = null;
            this.btnmaestros.OnDisabledState.IconRightImage = null;
            this.btnmaestros.onHoverState.BorderColor = System.Drawing.Color.LightSkyBlue;
            this.btnmaestros.onHoverState.BorderRadius = 35;
            this.btnmaestros.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnmaestros.onHoverState.BorderThickness = 1;
            this.btnmaestros.onHoverState.FillColor = System.Drawing.Color.LightSkyBlue;
            this.btnmaestros.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnmaestros.onHoverState.IconLeftImage = null;
            this.btnmaestros.onHoverState.IconRightImage = null;
            this.btnmaestros.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnmaestros.OnIdleState.BorderRadius = 35;
            this.btnmaestros.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnmaestros.OnIdleState.BorderThickness = 1;
            this.btnmaestros.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnmaestros.OnIdleState.ForeColor = System.Drawing.SystemColors.WindowText;
            this.btnmaestros.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnmaestros.OnIdleState.IconLeftImage")));
            this.btnmaestros.OnIdleState.IconRightImage = null;
            this.btnmaestros.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnmaestros.OnPressedState.BorderRadius = 35;
            this.btnmaestros.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnmaestros.OnPressedState.BorderThickness = 1;
            this.btnmaestros.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnmaestros.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnmaestros.OnPressedState.IconLeftImage = null;
            this.btnmaestros.OnPressedState.IconRightImage = null;
            this.btnmaestros.Size = new System.Drawing.Size(241, 60);
            this.btnmaestros.TabIndex = 2;
            this.btnmaestros.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnmaestros.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnmaestros.TextMarginLeft = 0;
            this.btnmaestros.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnmaestros.UseDefaultRadiusAndThickness = true;
            this.btnmaestros.Click += new System.EventHandler(this.btnmaestros_Click);
            // 
            // btnestudiantes
            // 
            this.btnestudiantes.AllowAnimations = true;
            this.btnestudiantes.AllowMouseEffects = true;
            this.btnestudiantes.AllowToggling = false;
            this.btnestudiantes.AnimationSpeed = 200;
            this.btnestudiantes.AutoGenerateColors = false;
            this.btnestudiantes.AutoRoundBorders = false;
            this.btnestudiantes.AutoSizeLeftIcon = false;
            this.btnestudiantes.AutoSizeRightIcon = true;
            this.btnestudiantes.BackColor = System.Drawing.Color.Transparent;
            this.btnestudiantes.BackColor1 = System.Drawing.Color.Transparent;
            this.btnestudiantes.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnestudiantes.BackgroundImage")));
            this.btnestudiantes.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnestudiantes.ButtonText = "Manejo Estudiantes";
            this.btnestudiantes.ButtonTextMarginLeft = 0;
            this.btnestudiantes.ColorContrastOnClick = 45;
            this.btnestudiantes.ColorContrastOnHover = 45;
            this.btnestudiantes.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnestudiantes.CustomizableEdges = borderEdges5;
            this.btnestudiantes.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnestudiantes.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnestudiantes.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnestudiantes.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnestudiantes.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnestudiantes.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnestudiantes.ForeColor = System.Drawing.SystemColors.WindowText;
            this.btnestudiantes.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnestudiantes.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnestudiantes.IconLeftPadding = new System.Windows.Forms.Padding(25, 3, 3, 3);
            this.btnestudiantes.IconMarginLeft = 11;
            this.btnestudiantes.IconPadding = 10;
            this.btnestudiantes.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnestudiantes.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnestudiantes.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnestudiantes.IconSize = 25;
            this.btnestudiantes.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnestudiantes.IdleBorderRadius = 35;
            this.btnestudiantes.IdleBorderThickness = 1;
            this.btnestudiantes.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnestudiantes.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnestudiantes.IdleIconLeftImage")));
            this.btnestudiantes.IdleIconRightImage = null;
            this.btnestudiantes.IndicateFocus = false;
            this.btnestudiantes.Location = new System.Drawing.Point(13, 197);
            this.btnestudiantes.Name = "btnestudiantes";
            this.btnestudiantes.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnestudiantes.OnDisabledState.BorderRadius = 35;
            this.btnestudiantes.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnestudiantes.OnDisabledState.BorderThickness = 1;
            this.btnestudiantes.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnestudiantes.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnestudiantes.OnDisabledState.IconLeftImage = null;
            this.btnestudiantes.OnDisabledState.IconRightImage = null;
            this.btnestudiantes.onHoverState.BorderColor = System.Drawing.Color.LightSkyBlue;
            this.btnestudiantes.onHoverState.BorderRadius = 35;
            this.btnestudiantes.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnestudiantes.onHoverState.BorderThickness = 1;
            this.btnestudiantes.onHoverState.FillColor = System.Drawing.Color.LightSkyBlue;
            this.btnestudiantes.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnestudiantes.onHoverState.IconLeftImage = null;
            this.btnestudiantes.onHoverState.IconRightImage = null;
            this.btnestudiantes.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnestudiantes.OnIdleState.BorderRadius = 35;
            this.btnestudiantes.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnestudiantes.OnIdleState.BorderThickness = 1;
            this.btnestudiantes.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnestudiantes.OnIdleState.ForeColor = System.Drawing.SystemColors.WindowText;
            this.btnestudiantes.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnestudiantes.OnIdleState.IconLeftImage")));
            this.btnestudiantes.OnIdleState.IconRightImage = null;
            this.btnestudiantes.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnestudiantes.OnPressedState.BorderRadius = 35;
            this.btnestudiantes.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnestudiantes.OnPressedState.BorderThickness = 1;
            this.btnestudiantes.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnestudiantes.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnestudiantes.OnPressedState.IconLeftImage = null;
            this.btnestudiantes.OnPressedState.IconRightImage = null;
            this.btnestudiantes.Size = new System.Drawing.Size(241, 60);
            this.btnestudiantes.TabIndex = 1;
            this.btnestudiantes.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnestudiantes.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnestudiantes.TextMarginLeft = 0;
            this.btnestudiantes.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnestudiantes.UseDefaultRadiusAndThickness = true;
            this.btnestudiantes.Click += new System.EventHandler(this.btnestudiantes_Click);
            // 
            // btnInicio
            // 
            this.btnInicio.AllowAnimations = true;
            this.btnInicio.AllowMouseEffects = true;
            this.btnInicio.AllowToggling = false;
            this.btnInicio.AnimationSpeed = 200;
            this.btnInicio.AutoGenerateColors = false;
            this.btnInicio.AutoRoundBorders = false;
            this.btnInicio.AutoSizeLeftIcon = false;
            this.btnInicio.AutoSizeRightIcon = true;
            this.btnInicio.BackColor = System.Drawing.Color.Transparent;
            this.btnInicio.BackColor1 = System.Drawing.Color.Transparent;
            this.btnInicio.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnInicio.BackgroundImage")));
            this.btnInicio.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInicio.ButtonText = "Inicio";
            this.btnInicio.ButtonTextMarginLeft = 0;
            this.btnInicio.ColorContrastOnClick = 45;
            this.btnInicio.ColorContrastOnHover = 45;
            this.btnInicio.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnInicio.CustomizableEdges = borderEdges6;
            this.btnInicio.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnInicio.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInicio.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInicio.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInicio.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnInicio.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnInicio.ForeColor = System.Drawing.SystemColors.WindowText;
            this.btnInicio.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInicio.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnInicio.IconLeftPadding = new System.Windows.Forms.Padding(25, 3, 3, 3);
            this.btnInicio.IconMarginLeft = 11;
            this.btnInicio.IconPadding = 10;
            this.btnInicio.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnInicio.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnInicio.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnInicio.IconSize = 25;
            this.btnInicio.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnInicio.IdleBorderRadius = 35;
            this.btnInicio.IdleBorderThickness = 1;
            this.btnInicio.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnInicio.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnInicio.IdleIconLeftImage")));
            this.btnInicio.IdleIconRightImage = null;
            this.btnInicio.IndicateFocus = false;
            this.btnInicio.Location = new System.Drawing.Point(13, 127);
            this.btnInicio.Name = "btnInicio";
            this.btnInicio.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInicio.OnDisabledState.BorderRadius = 35;
            this.btnInicio.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInicio.OnDisabledState.BorderThickness = 1;
            this.btnInicio.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInicio.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInicio.OnDisabledState.IconLeftImage = null;
            this.btnInicio.OnDisabledState.IconRightImage = null;
            this.btnInicio.onHoverState.BorderColor = System.Drawing.Color.LightSkyBlue;
            this.btnInicio.onHoverState.BorderRadius = 35;
            this.btnInicio.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInicio.onHoverState.BorderThickness = 1;
            this.btnInicio.onHoverState.FillColor = System.Drawing.Color.LightSkyBlue;
            this.btnInicio.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnInicio.onHoverState.IconLeftImage = null;
            this.btnInicio.onHoverState.IconRightImage = null;
            this.btnInicio.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnInicio.OnIdleState.BorderRadius = 35;
            this.btnInicio.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInicio.OnIdleState.BorderThickness = 1;
            this.btnInicio.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnInicio.OnIdleState.ForeColor = System.Drawing.SystemColors.WindowText;
            this.btnInicio.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnInicio.OnIdleState.IconLeftImage")));
            this.btnInicio.OnIdleState.IconRightImage = null;
            this.btnInicio.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnInicio.OnPressedState.BorderRadius = 35;
            this.btnInicio.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInicio.OnPressedState.BorderThickness = 1;
            this.btnInicio.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnInicio.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnInicio.OnPressedState.IconLeftImage = null;
            this.btnInicio.OnPressedState.IconRightImage = null;
            this.btnInicio.Size = new System.Drawing.Size(241, 60);
            this.btnInicio.TabIndex = 0;
            this.btnInicio.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnInicio.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnInicio.TextMarginLeft = 0;
            this.btnInicio.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnInicio.UseDefaultRadiusAndThickness = true;
            this.btnInicio.Click += new System.EventHandler(this.btnInicio_Click);
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.bunifuPictureBox1);
            this.panel3.Controls.Add(this.btnuser);
            this.panel3.Controls.Add(this.titulo);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel3.Location = new System.Drawing.Point(262, 44);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(938, 85);
            this.panel3.TabIndex = 3;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuPictureBox1.BorderRadius = 18;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(717, 24);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(36, 36);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 12;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // btnuser
            // 
            this.btnuser.AllowAnimations = true;
            this.btnuser.AllowMouseEffects = true;
            this.btnuser.AllowToggling = false;
            this.btnuser.AnimationSpeed = 200;
            this.btnuser.AutoGenerateColors = false;
            this.btnuser.AutoRoundBorders = false;
            this.btnuser.AutoSizeLeftIcon = false;
            this.btnuser.AutoSizeRightIcon = false;
            this.btnuser.BackColor = System.Drawing.Color.Transparent;
            this.btnuser.BackColor1 = System.Drawing.Color.Transparent;
            this.btnuser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnuser.BackgroundImage")));
            this.btnuser.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnuser.ButtonText = "Aysha";
            this.btnuser.ButtonTextMarginLeft = 0;
            this.btnuser.ColorContrastOnClick = 45;
            this.btnuser.ColorContrastOnHover = 45;
            this.btnuser.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnuser.CustomizableEdges = borderEdges7;
            this.btnuser.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnuser.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnuser.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnuser.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnuser.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnuser.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnuser.ForeColor = System.Drawing.Color.Black;
            this.btnuser.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnuser.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnuser.IconLeftPadding = new System.Windows.Forms.Padding(11, 0, 0, 0);
            this.btnuser.IconMarginLeft = 11;
            this.btnuser.IconPadding = 10;
            this.btnuser.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnuser.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnuser.IconRightPadding = new System.Windows.Forms.Padding(0, 0, 25, 0);
            this.btnuser.IconSize = 20;
            this.btnuser.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnuser.IdleBorderRadius = 35;
            this.btnuser.IdleBorderThickness = 1;
            this.btnuser.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnuser.IdleIconLeftImage = null;
            this.btnuser.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btnuser.IdleIconRightImage")));
            this.btnuser.IndicateFocus = false;
            this.btnuser.Location = new System.Drawing.Point(693, 17);
            this.btnuser.Name = "btnuser";
            this.btnuser.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnuser.OnDisabledState.BorderRadius = 35;
            this.btnuser.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnuser.OnDisabledState.BorderThickness = 1;
            this.btnuser.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnuser.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnuser.OnDisabledState.IconLeftImage = null;
            this.btnuser.OnDisabledState.IconRightImage = null;
            this.btnuser.onHoverState.BorderColor = System.Drawing.Color.LightSkyBlue;
            this.btnuser.onHoverState.BorderRadius = 35;
            this.btnuser.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnuser.onHoverState.BorderThickness = 1;
            this.btnuser.onHoverState.FillColor = System.Drawing.Color.LightSkyBlue;
            this.btnuser.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnuser.onHoverState.IconLeftImage = null;
            this.btnuser.onHoverState.IconRightImage = null;
            this.btnuser.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnuser.OnIdleState.BorderRadius = 35;
            this.btnuser.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnuser.OnIdleState.BorderThickness = 1;
            this.btnuser.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnuser.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnuser.OnIdleState.IconLeftImage = null;
            this.btnuser.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton24.OnIdleState.IconRightImage")));
            this.btnuser.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnuser.OnPressedState.BorderRadius = 35;
            this.btnuser.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnuser.OnPressedState.BorderThickness = 1;
            this.btnuser.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnuser.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnuser.OnPressedState.IconLeftImage = null;
            this.btnuser.OnPressedState.IconRightImage = null;
            this.btnuser.Size = new System.Drawing.Size(192, 50);
            this.btnuser.TabIndex = 4;
            this.btnuser.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnuser.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnuser.TextMarginLeft = 0;
            this.btnuser.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnuser.UseDefaultRadiusAndThickness = true;
            // 
            // titulo
            // 
            this.titulo.Font = new System.Drawing.Font("Century Gothic", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.titulo.ForeColor = System.Drawing.Color.DarkGray;
            this.titulo.Location = new System.Drawing.Point(79, 35);
            this.titulo.Name = "titulo";
            this.titulo.Size = new System.Drawing.Size(494, 30);
            this.titulo.TabIndex = 3;
            this.titulo.Text = "...";
            // 
            // panelDesktop
            // 
            this.panelDesktop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelDesktop.Location = new System.Drawing.Point(262, 129);
            this.panelDesktop.Name = "panelDesktop";
            this.panelDesktop.Size = new System.Drawing.Size(938, 471);
            this.panelDesktop.TabIndex = 4;
            // 
            // Menu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1200, 600);
            this.Controls.Add(this.panelDesktop);
            this.Controls.Add(this.panel3);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Menu";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Menu_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.Label titulo;
        private Bunifu.UI.WinForms.BunifuFormControlBox bunifuFormControlBox1;
        private System.Windows.Forms.Panel panelDesktop;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnInicio;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSalir;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnconfiguracion;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnmaestros;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnestudiantes;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnuser;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnocultar;
    }
}

